### ISSUE TITLE
UI/UX design for Dnotebook 

### ISSUE THREAD

**Issue by risenW** [opensource9ja/dnotebook-react#1]
We need a newer and better design for Dnotebook. The current design is shown below:
<img width="1268" alt="Screen Shot 2020-11-11 at 9 02 22 PM" src="https://user-images.githubusercontent.com/29900845/98858939-b6aab300-2461-11eb-8d51-4dbd54109135.png">

You can view the current Dnotebook live [here](https://playnotebook.jsdata.org/)

For inspiration, see [Colab](https://colab.research.google.com/drive/1qSHfUuQHnfbqRuYwWC7Je7xKTrDdC9CD?usp=sharing) and [Jupyter lab interface](https://mybinder.org/v2/gh/jupyterlab/jupyterlab-demo/master?urlpath=lab/tree/demo)

Some features Ideas:

* A File menu for accessing directories
* Icon Shortcuts

**Comment by adolphchris19** [comment]
I would love to help in improving the UI

**Comment by adolphchris19** [comment]
I tried accessing the links you sent, as inspirations, I could not access any also.

**Comment by risenW** [comment]
> I tried accessing the links you sent, as inspirations, I could not access any also.

Thanks for volunteering. I have updated the links above, let me know if you can access them now.

**Comment by adolphchris19** [comment]
I can access the files now, thank you. I am trying to send you a DM on twitter but I can't. My handle is @dev_khris

I'd like to ask some more questions and also invite you to the design file

**Comment by risenW** [comment]
> I can access the files now, thank you. I am trying to send you a DM on twitter but I can't. My handle is @dev_khris
> 
> I'd like to ask some more questions and also invite you to the design file

Sure, I'll dm you now

**Comment by ifenium** [comment]
Hi @adolphchris19  I'll be happy to help if you need an extra hand.

**Comment by adolphchris19** [comment]
> Hi @adolphchris19 I'll be happy to help if you need an extra hand.

Yes, shoot me a message on twitter @dev_khris. Thank you.

**Comment by sophisticateddev** [comment]
> I would love to help in improving the UI

I can join you in improving the UI design

**Comment by adolphchris19** [comment]
> > I would love to help in improving the UI
> 
> I can join you in improving the UI design

Sure. Shoot me a DM on twitter. @dev_khris

**Comment by risenW** [comment]
@adolphchris19 any update on the design?

**Comment by ifenium** [comment]
@adolphchris19 has been unavailable lately, can send a DM to share what I've worked on ? @risenW

**Comment by risenW** [comment]
> @adolphchris19 has been unavailable lately, can send a DM to share what I've worked on ? @risenW

@ifenium, @adolphchris19 shared [these designs](https://www.figma.com/file/g4KON67i6B0CIejHp78GU4/Playnotebook?node-id=0%3A1) with me, is yours different from it? Or did you work with him on it

**Comment by ifenium** [comment]
@risenW I worked on the one positioned at the far left. I shared them with him after I was done and we we were supposed to make modifications, but he hasn't been available for some reasons since then to do so.

![m](https://user-images.githubusercontent.com/40589517/100217430-bb687000-2f13-11eb-91eb-a74d9ab74aeb.png)

**Comment by risenW** [comment]
> @risenW I worked on the one positioned at the far left. I shared them with him after I was done and we we were supposed to make modifications, but he hasn't been available for some reasons since then to do so.
> 
> ![m](https://user-images.githubusercontent.com/40589517/100217430-bb687000-2f13-11eb-91eb-a74d9ab74aeb.png)

Can you add and share the modified link here?

**Comment by adolphchris19** [comment]
@ifenium @risenW  I am really sorry for not communicating about my tight schedule this past week. I will message @ifenium and see how we can push an update to you today.

**Comment by risenW** [comment]
> @ifenium @risenW I am really sorry for not communicating about my tight schedule this past week. I will message @ifenium and see how we can push an update to you today.

That's fine, I definitely understand. Well done

**Comment by ifenium** [comment]
Good day,  @risenW will the "Getting Started" page be redesigned too because it seems like it's hosted on GitBook and not coded directly on the website?

**Comment by risenW** [comment]
> Good day, @risenW will the "Getting Started" page be redesigned too because it seems like it's hosted on GitBook and not coded directly on the website?

No it does not need to be redesigned. Thanks

**Comment by risenW** [comment]
@adolphchris19 @ifenium are the designs good to go? We want to get started on the front end work by weekend.

**Comment by ifenium** [comment]
@risenW Here's the link the finished design
https://www.figma.com/file/g4KON67i6B0CIejHp78GU4/Playnotebook?node-id=52%3A2

**Comment by AceTheCreator** [comment]
@steveoni @risenW I have some questions about the UI designs, who I'm I to contact?

**Comment by risenW** [comment]
You can talk @adolphchris19 and @ifenium

**Comment by AceTheCreator** [comment]
@adolphchris19 @ifenium I have some questions about the UI designs, I'd really appreciate if you guys can help.

**Comment by adolphchris19** [comment]
@AceTheCreator Hello bro, yeah, you can ask your questions. You can message me on whatsapp 09051694275 for faster communication still.

**Comment by risenW** [comment]
Closing this as UI design has been completed and dev work is in progress
