### ISSUE TITLE
Add ploty functionality

### ISSUE THREAD

**Issue by AceTheCreator** [opensource9ja/dnotebook-react#14]
Dnotebook plot functionality is not yet implemented

**Comment by AceTheCreator** [comment]
@steveoni @risenW is there a built in plotting functionality in danfojs or an external library is been you use when plotting?

**Comment by risenW** [comment]
We support Plotly graph, so the plot functions basically uses Plotly (When it is installed) to make charts.

**Comment by AceTheCreator** [comment]
Ok, I've implemented it I'll submit a pull request closing this issue tomorrow.

**Comment by AceTheCreator** [comment]
@risenW I've created a PR that will close this issue
