### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by AceTheCreator** [opensource9ja/dnotebook-react#3]
Need someone to implement the navigation bar.
P.S. It must be responsive.

**Comment by folafunmi-db** [comment]
I volunteer, I can get it done on Monday but where would I push it to? And do you suggest CRA or NextJS? Also would you prefer vanilla css, sass or tailwind?

**Comment by folafunmi-db** [comment]
Also, am I to include a theme switched for dark mode, if so where do I put it? And do I assume that the responsive layout would substitute the nav links with a hamburger menu? Because it's not shown in the Figma file.

**Comment by alphabet-codes** [comment]
@folafunmi-db I'm waiting for @steveoni to make me a contributor to the project's repo in other to lead the project.

**Comment by steveoni** [comment]
@alphabet-codes I will.

**Comment by steveoni** [comment]
@alphabet-codes I sent an invite

**Comment by alphabet-codes** [comment]
@folafunmi-db you can start working on this issue now. The styles should be writing in CSS-IN-JS, fork the project's repo in other to get started.

**Comment by folafunmi-db** [comment]
I'd get started this week, just need to finish up something else for. Also, I assume we're using CRA and not Next JS?

**Comment by steveoni** [comment]
@alphabet-codes @folafunmi-db  any progress update? Any blockers and what's the timeline for the project completion, cause we need a major milestone on this before this weekend.

**Comment by alphabet-codes** [comment]
> I'd get started this week, just need to finish up something else for. Also, I assume we're using CRA and not Next JS?

@folafunmi-db fork the project's repo it's bootstrapped by CRA

**Comment by alphabet-codes** [comment]
> @alphabet-codes @folafunmi-db  any progress update? Any blockers and what's the timeline for the project completion, cause we need a major milestone on this before this weekend.

@steveoni I'm currently working on it and I'll submit a pull request tomorrow and there's no blockers for now. I'll ensure there's a major milestone before the week runs out.

**Comment by folafunmi-db** [comment]
@alphabet-codes I've submitted a pull request, please review.
