### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by AceTheCreator** [opensource9ja/dnotebook-react#6]
Build and implement dnotebook about page. visit [https://www.figma.com/file/g4KON67i6B0CIejHp78GU4/Playnotebook?node-id=52%3A2](url) to view the UI design.

**Comment by risenW** [comment]
@AceTheCreator What's the update on this as well. We'd love to continue where you left, I understand you don't have lots of time on end. Just push what you have done so far.

**Comment by AceTheCreator** [comment]
@risenW I'd love to continue managing this project if you don't mind. My main reason for not being responsive was because i had a personal issue last month that affected my ability to code. But everything is back to normal all thanks to God.

**Comment by risenW** [comment]
> @risenW I'd love to continue managing this project if you don't mind. My main reason for not being responsive was because i had a personal issue last month that affected my ability to code. But everything is back to normal all thanks to God.

My bad, I totally understand now. And by the way, just saw some screenshots of your work, it's amazing! 👍🏽

**Comment by risenW** [comment]
Fixed in #12
